language: python

python:
    - "3.6"

install:
    - pip install scipy
    - pip install numpy
    - pip install hypothesis
    - pip install matplotlib

script:
    - pytest -s -v --cov pycontest --cov-config .coveragerc --cov-report xml:cov.xml tests
