language: python

python:
    - "3.6"

install:
    - pip install scipy
    - pip install numpy
    - pip install hypothesis
    - pip install matplotlib

script:
    - pytest --cov pydra --cov-config .coveragerc --cov-report xml:cov.xml
